safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /jekyll_demo
url: http://localhost:4000

permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 吕管明
  email: lvgm2013@gmail.com
  link: http://lvgm.cn
  weibo: http://weibo.com/lguanming
  github: http://github.com/lvguanming

# 站点信息
title: 吕管明的网络日志 
description: 吕管明的网络日志，记录生活的点滴。
url: http://lvgm.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /images/gavatar.png
favicon: /images/favicon.ico

# google analytics 设置
#ga:
#  id: UA-43667383-1
#  url: lvgm.cn

# disqus 设置
disqus:
  shortname: suyan-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
